mapping = {
    'Sk.builtin.__import__':'',
    "Sk.builtin.abs": "",
    "Sk.builtin.all": "",
    "Sk.builtin.any": "",
    "Sk.builtin.apply_": "",
    "Sk.builtin.ascii": "",
    "Sk.builtin.asnum$": "",
    "Sk.builtin.asnum$nofloat": "",
    "Sk.builtin.assk$": "",
    "Sk.builtin.bin": "",
    "Sk.builtin.buffer": "",
    "Sk.builtin.bytearray": "",
    "Sk.builtin.callable": "",
    "Sk.builtin.callable_iter_": "",

    "Sk.builtin.chr": "",
    "Sk.builtin.coerce": "",
    "Sk.builtin.delattr": "",
    "Sk.builtin.dir": "",
    "Sk.builtin.divmod": "",
    "Sk.builtin.eval_": "",
    "Sk.builtin.execfile": "",
    "Sk.builtin.fabs": "",
    "Sk.builtin.file": "",
    "Sk.builtin.filter": "",
    "Sk.builtin.format": "",
    "Sk.builtin.getExcInfo": "",
    "Sk.builtin.getattr": "",
    "Sk.builtin.globals": "",
    "Sk.builtin.hasattr": "",
    "Sk.builtin.hash": "",
    "Sk.builtin.help": "",
    "Sk.builtin.hex": "",
    "Sk.builtin.id": "",
    "Sk.builtin.input": "",
    "Sk.builtin.int2str_": "",
    "Sk.builtin.intern": "",
    "Sk.builtin.isinstance": "",
    "Sk.builtin.issubclass": "",
    "Sk.builtin.iter": "",
    "Sk.builtin.jseval": "",
    "Sk.builtin.jsmillis": "",
    "Sk.builtin.len": "",
    "Sk.builtin.listSlice": "",
    "Sk.builtin.locals": "",
    "Sk.builtin.makeGenerator": "",
    "Sk.builtin.make_structseq": "",
    "Sk.builtin.map": "",
    "Sk.builtin.max": "",
    "Sk.builtin.memoryview": "",
    "Sk.builtin.min": "",
    "Sk.builtin.module": "",
    "Sk.builtin.next_": "",
    "Sk.builtin.oct": "",
    "Sk.builtin.open": "",
    "Sk.builtin.ord": "",
    "Sk.builtin.pow": "",
    "Sk.builtin.print": "",
    "Sk.builtin.pyCheckArgs": "",
    "Sk.builtin.pyCheckArgsLen": "",
    "Sk.builtin.pyCheckType": "",
    "Sk.builtin.quit": "",
    "Sk.builtin.range": "",
    "Sk.builtin.raw_input": "",
    "Sk.builtin.reduce": "",
    "Sk.builtin.reload": "",
    "Sk.builtin.repr": "",
    "Sk.builtin.reversed": "",
    "Sk.builtin.round": "",
    "Sk.builtin.seq_iter_": "",
    "Sk.builtin.setattr": "",
    "Sk.builtin.sorted": "",
    "Sk.builtin.structseq_types": "",
    "Sk.builtin.sum": "",
    "Sk.builtin.timSort": "",
    "Sk.builtin.unichr": "",
    "Sk.builtin.vars": "",
    "Sk.builtin.wrapper_descriptor": "",
    "Sk.builtin.xrange": "",
    "Sk.builtin.zip": "",

    
    ###### HELPERS #######
    
    ###### PY2 ONLY ######


    ###### BUILTIN FUNCS ######

    ###### CHECKS ######
    "Sk.builtin.checkAnySet": "checkAnySet",
    "Sk.builtin.checkBool": "checkBool",
    "Sk.builtin.checkBytes": "checkBytes",
    "Sk.builtin.checkCallable": "checkCallable",
    "Sk.builtin.checkClass": "checkClass",
    "Sk.builtin.checkComplex": "checkComplex",
    "Sk.builtin.checkDataDescr": "checkDataDescr",
    "Sk.builtin.checkFloat": "checkFloat",
    "Sk.builtin.checkFunction": "checkFunction",
    "Sk.builtin.checkInt": "checkInt",
    "Sk.builtin.checkIterable": "checkIterable",
    "Sk.builtin.checkMapping": "checkMapping",
    "Sk.builtin.checkNone": "checkNone",
    "Sk.builtin.checkNumber": "checkNumber",
    "Sk.builtin.checkSequence": "checkSequence",
    "Sk.builtin.checkString": "checkString",

    ###### ERROR" ######
    "Sk.builtin.AssertionError": "pyAssertionError",
    "Sk.builtin.AttributeError": "pyAttributeError",
    "Sk.builtin.BaseException": "pyBaseException",
    "Sk.builtin.Exception": "pyException",
    "Sk.builtin.ExternalError": "pyExternalError",
    "Sk.builtin.IOError": "pyIOError",
    "Sk.builtin.ImportError": "pyImportError",
    "Sk.builtin.IndentationError": "pyIndentationError",
    "Sk.builtin.IndexError": "pyIndexError",
    "Sk.builtin.KeyError": "pyKeyError",
    "Sk.builtin.LookupError": "pyLookupError",
    "Sk.builtin.NameError": "pyNameError",
    "Sk.builtin.NegativePowerError": "pyNegativePowerError",
    "Sk.builtin.NotImplementedError": "pyNotImplementedError",
    "Sk.builtin.OperationError": "pyOperationError",
    "Sk.builtin.OverflowError": "pyOverflowError",
    "Sk.builtin.RecursionError": "pyRecursionError",
    "Sk.builtin.RuntimeError": "pyRuntimeError",
    "Sk.builtin.StopIteration": "pyStopIteration",
    "Sk.builtin.SuspensionError": "pySuspensionError",
    "Sk.builtin.SyntaxError": "pySyntaxError",
    "Sk.builtin.SystemError": "pySystemError",
    "Sk.builtin.SystemExit": "pySystemExit",
    "Sk.builtin.TimeLimitError": "pyTimeLimitError",
    "Sk.builtin.TypeError": "pyTypeError",
    "Sk.builtin.UnboundLocalError": "pyUnboundLocalError",
    "Sk.builtin.UnicodeDecodeError": "pyUnicodeDecodeError",
    "Sk.builtin.UnicodeEncodeError": "pyUnicodeEncodeError",
    "Sk.builtin.ValueError": "pyValueError",
    "Sk.builtin.ZeroDivisionError": "pyZeroDivisionError",

    ###### ITERATOR HELPERS #######

    ###### TYPES ######
    "Sk.builtin.bool": "pyBool",
    "Sk.builtin.bool.true$": "pyTrue",
    "Sk.builtin.bool.false$": "pyFalse",
    "Sk.builtin.bytes": "pyBytes",
    "Sk.builtin.classmethod": "pyClassMethod",
    "Sk.builtin.classmethod_descriptor": "pyClassmethodDescriptor",
    "Sk.builtin.complex": "pyComplex",
    "Sk.builtin.dict": "pyDict",
    "Sk.builtin.enumerate": "pyEnumerate",
    "Sk.builtin.filter_": "pyFilter",
    "Sk.builtin.float_": "pyFloat",
    "Sk.builtin.frozenset": "pyFrozenSet",
    "Sk.builtin.func": "pyFunc",
    "Sk.builtin.generator": "pyGenerator",
    "Sk.builtin.getset_descriptor": "pyGetSetDescriptor",
    "Sk.builtin.int_": "pyInt",
    "Sk.builtin.list": "pyList",
    "Sk.builtin.lng": "pyLong",
    "Sk.builtin.map_": "pyMap",
    "Sk.builtin.mappingproxy": "pyMappingProxy",
    "Sk.builtin.method": "pyMethod",
    "Sk.builtin.method_descriptor": "pyMethodDescriptor",
    "Sk.builtin.method_wrapper": "pyMethodWrapper",
    "Sk.builtin.none": "pyNoneType",
    "Sk.builtin.none.none$": "pyNone",
    "Sk.builtin.NotImplemented": "pyNotImplementedType",
    "Sk.builtin.NotImplemented.NotImplemented$": "pyNotImplemented",
    "Sk.builtin.property": "pyProperty",
    "Sk.builtin.object": "pyObject",
    "Sk.builtin.range_": "pyRange",
    "Sk.builtin.set": "pySet",
    "Sk.builtin.slice": "pySlice",
    "Sk.builtin.sk_method": "pyBuiltinMethod",
    "Sk.builtin.staticmethod": "pyStaticMethod",
    "Sk.builtin.str": "pyStr",
    "Sk.builtin.super_": "pySuper",
    "Sk.builtin.tuple": "pyTuple",
    "Sk.builtin.type": "pyType",
    "Sk.builtin.zip_": "pyZip",
}
