export { configure, builtins, ffi, sys } from "./internal";

export const types = {
    pyObject,
    pyType,
    pyFunc,
    pyBuiltinFuncOrMethod,
    pyMethod,
    pyStr,
    pyBytes,
    pyList,
    pyTuple,
    pySet,
    pyFrozenSet,
    pyBool,
    pyInt,
    pyFloat,
    pyComplex,
    pyIterator,
    pySlice,
    pyRange,
    pyModule,
    pyStaticMethod,
    pyClassMethod,
    pyProperty,
    pyMappingProxy,
    pyWrapperDescr,
    pyMethodWrapper,
    pyGetSetDescr,
    pyMethodDescr,
    pyClassMethodDescr,

    pyExc,
    pyTrue,
    pyFalse,
    pyNone,
    pyNotImplemented,
};

export const misceval = {
    asIndex,
    asIndexSized,
    asIndexOrThrow,
    asyncToPromise,
    pyCall,
    pyCallAsync,
    pyCallOrSuspend,
    buildClass,
    chainOrSuspend,
    iterForOrSuspend,
    iterArrayOrSuspend,
    arrayFromIterable,
    tryCatchOrSuspend,
    retryOptionalSuspensionOrThrow,
    Suspension,
    Break,
};

export const abstr = {
    buildNativeClass,
    buildIteratorClass,
    setUpInheritance,
    setUpModuleMethods,

    keywordArrayToNamedArgs,
    keywordArrayFromMapping,
    keywordArrayToDict,
    keywordArrayFromHashMap,

    typeName,
    objectRepr,
    objectGetItem,
    objectSetItem,
    objectDelItem,
    objectGetAttr,
    objectSetAttr,
    objectDelAttr,
    objectGetIter,
    objectFormat,
    objectLookupSpecial,
    objectRichCompare,
    // objectIsSubType,
    // objectIsInstance,
    objectHash,
    objectIsTrue,
    objectLen,

    numberBinOp,
    numberInplaceBinOp,
    numberUnaryOp,
};

export const checks = {
    checkIndex,
    checkFloat,
    checkInt,
    checkNumber,
    checkComplex,
    checkClass,
    checkMapping,
    checkAnySet,

    pyCheckType,

    checkArgsLen,
    checkNoArgs,
    checkNoKwargs,
    checkOneArg,
};

import {
    pyObject,
    pyType,
    pyFunc,
    pyBuiltinFuncOrMethod,
    pyMethod,
    pyStr,
    pyBytes,
    pyList,
    pyTuple,
    pySet,
    pyFrozenSet,
    pyBool,
    pyInt,
    pyFloat,
    pyComplex,
    pyIterator,
    pySlice,
    pyModule,
    pyRange,
    pyExc,
    pyTrue,
    pyFalse,
    pyNone,
    pyNotImplemented,
    pyStaticMethod,
    pyClassMethod,
    pyProperty,
    pyMappingProxy,
    pyWrapperDescr,
    pyMethodWrapper,
    pyGetSetDescr,
    pyMethodDescr,
    pyClassMethodDescr,
    pyCall,
    pyCallOrSuspend,
    pyCallAsync,

    // pyIterNext,
    arrayFromIterable,
    Suspension,
    asyncToPromise,
    Break,
    // breakSuspension,
    chainOrSuspend,
    iterForOrSuspend,
    iterArrayOrSuspend,
    tryCatchOrSuspend,
    retryOptionalSuspensionOrThrow,
    asIndex,
    asIndexSized,
    asIndexOrThrow,

    // toPy,
    // remapToPy,
    // toPyDict,
    // toPyStr,
    // toPyList,
    // toPyTuple,
    // toPySet,
    // toPyNumber,
    // toPyInt,
    // toPyFloat,
    // numberToPy,

    // toJs,
    // remapToJs,
    // toJsArray,
    // toJsBool,
    // toJsNumber,
    // toJsString,
    // toJsHashMap,
    checkIndex,
    checkFloat,
    checkInt,
    checkNumber,
    checkComplex,
    checkClass,
    checkMapping,
    checkAnySet,
    pyCheckType,
    checkArgsLen,
    checkNoArgs,
    checkNoKwargs,
    checkOneArg,
    keywordArrayToNamedArgs,
    keywordArrayFromMapping,
    keywordArrayToDict,
    keywordArrayFromHashMap,

    buildClass,
    buildNativeClass,
    buildIteratorClass,
    setUpModuleMethods,
    setUpInheritance,
    typeName,
    objectRepr,
    objectGetItem,
    objectSetItem,
    objectDelItem,
    objectGetAttr,
    objectSetAttr,
    objectDelAttr,
    objectGetIter,
    objectFormat,
    objectLookupSpecial,
    objectRichCompare,
    objectHash,
    // objectIsSubType,
    // objectIsInstance,
    objectIsTrue,
    objectLen,
    numberBinOp,
    numberInplaceBinOp,
    numberUnaryOp,

    // importModule,
    // importMainWithBody,

    // compile,
    // unFixReserved,
    // fixReserved,

    // sysModules,
    // env,
    // configure,
} from "./internal";
